### ISSUE TITLE
[Crash] Crashes with OptiFine

### ISSUE THREAD

**Issue by meerity** [SuperMartijn642/Fusion#10]
**Version Info**
- Minecraft 1.18.2
- Fusion 1.0.3

**Are you using OptiFine:** Yes 

**Steps to Reproduce**
Launch Minecraft

**Crash report (~/logs/latest.log)**

[crash-2023-07-12_15.25.27-client.txt](https://github.com/SuperMartijn642/Fusion/files/12027845/crash-2023-07-12_15.25.27-client.txt)

**Comment by SuperMartijn642** [comment]
OptiFine is closed source, so not much I can do about this. Either report it to OptiFine or use better alternatives such as Iris or Oculus.
