### ISSUE TITLE
[Question] Is smooth lighting supposed to not work on connected blocks or is it a bug?

### ISSUE THREAD

**Issue by fr3dr** [SuperMartijn642/Fusion#12]
**Question**

Is smooth lighting supposed to not work on connected blocks or is it a bug?

I am making a Modpack and i was testing the connected blocks and i figured out that smooth lighting doesn't seem to work on them?

**Comment by SuperMartijn642** [comment]
Please report things like this as a bug and not a question, the bug template asks for all the version info I need 😛

Of course smooth lighting should work for the blocks with connecting textures.
What versions of Minecraft and of Fusion are you using? Are you using Fabric or Forge? What blocks does this happen for and under what situation? Are you using any other mods?

**Comment by SuperMartijn642** [comment]
Closing this as it was resolved in #13.
