### ISSUE TITLE
[Bug] Smooth lighting doesnt work on connecting blocks

### ISSUE THREAD

**Issue by fr3dr** [SuperMartijn642/Fusion#13]
**Version Info**
- Minecraft, 1.20.1
- Fusion, fusion-1.0.3-forge-mc1.20

**Are you using OptiFine:** No

**Description of the Bug**
Smooth lighting doesn't work on connecting blocks

**Steps to Reproduce**
Place a light source on a connected block

**Screenshots**
https://media.essential.gg/e9e7ec53-2706-451b-7e4d-e5484e411200
![image](https://github.com/SuperMartijn642/Fusion/assets/46770388/b8e6d4db-38d4-4d6b-b552-8bba2999e3d9)

Full mod list:
    [Rechiseled: Create (by SuperMartijn642)]
    [Sophisticated Core (by P3pp3rF1y)]
    [Entity Culling Fabric/Forge (by tr7zw)]
    [Create Slice & Dice (by possible_triangle)]
    [Iris & Oculus Flywheel Compat (by leon_mout)]
    [Corpse (by henkelmax)]
    [Clumps (by Jaredlll08)]
    [Just Enough Items (JEI) (by mezz)]
    [Kotlin for Forge (by thedarkcolour)]
    [FerriteCore (Forge) (by malte0811)]
    [Curios API (Forge) (by TheIllusiveC4)]
    [SuperMartijn642's Config Lib (by SuperMartijn642)]
    [ModernFix (by embeddedt)]
    [Sophisticated Backpacks (by P3pp3rF1y)]
    [Inventory HUD+ (by dmitrylovin)]
    [Canary (by AbdElAziz333)]
    [Oculus (by Asek3)]
    [Rubidium (by Asek3)]
    [Jade 🔍 (by Snownee)]
    [Inventory Sorter (by cpw)]
    [Xaero's Minimap (by xaero96)]
    [Xaero's World Map (by xaero96)]
    [Create (by simibubi)]
    [Fusion (Connected Textures) (by SuperMartijn642)]
    [AppleSkin (by squeek502)]
    [Mouse Tweaks (by YaLTeR)]
    [Jade Addons (Forge) (by Snownee)]
    [Rechiseled (by SuperMartijn642)]
    [Sound Physics Remastered (by henkelmax)]
    [Farmer's Delight (by vectorwing)]
    [SuperMartijn642's Core Lib (by SuperMartijn642)]
    [AI Improvements (by QueenOfMissiles)]
    [ESSENTIAL Mod (by SparkUniverse_)]
    [Sophisticated Storage (by P3pp3rF1y)]
    [Magnesium/Rubidium Extras (by Anthxny)]
    [Magnesium/Rubidium Dynamic Lights (by Anthxny)]

**Comment by SuperMartijn642** [comment]
Thanks, this report is excellent!

Seems I accidentally set `ambientocclusion` to false by default for Fusion's connecting model generator, whoops. I have fixed the issue in Fusion and regenerated the model files for Rechiseled and Rechiseled: Create, so should be fixed now.
Thank you for reporting the issue!
