### ISSUE TITLE
Compatible with optifine ressourcepacks

### ISSUE THREAD

**Issue by Lendill** [SuperMartijn642/Fusion#15]
Simple question /suggestion:

Please make this mod compatible with optifines ctm system. It would help immensily.

**Comment by SuperMartijn642** [comment]
No

**Comment by AngellusMortis** [comment]
So, I understand why you would not want to support Optifine's format, but I just want to make a case for you to reconsider. 

Optfine bad. Closed source. I get it. I think everyone does at this point. But as a content creator (I am not one, just seen this pattern many times over the years), which am I going to support? The closed standard that is popular and will definitely get me users and donations/money? Or the open standard that a lot less people use? Every resource pack I have seen supports Optifine (or by extension Connectedness/Continuity which is not available for 1.20 forge). But I have seen zero resource packs that support literally any other format _for Forge_. 

If we want to take market share _from_ Optifine and kill it, we need to make it is "simple" choice for content creators to switch to the open-source solutions. Supporting the Optifine format allows creators to do that. At least until Optifine stops being used (we are slowly getting there in a 1.18+ world). Then the Optifine format can be deprecated for the more open one.
