### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by OliverWolf621** [SuperMartijn642/Fusion#16]
**Version Info**
- Minecraft, 1.18.2
- Fusion, ...?
- Forge 40.2.10

**Are you using OptiFine:** Yes or no
No
**Description of the Bug**
Teleport cost does not change with distance, stuck at 500. Configs are all default, on a new installation. Nothing in latest or debug log

**Steps to Reproduce**
Unsure, I had made a new installation on the CurseForge app, installed the mod and it's 2 dependencies, opened the game and immediately made a new world, built a portal and set the destination literally 4 blocks away and the cost read 500. Tried somethere else, still 500...

**Screenshots**
...
![2023-08-16_20 47 31](https://github.com/SuperMartijn642/Fusion/assets/142481537/8229b40c-1e88-4e9c-a297-6d6d3c80bf05)

**Comment by SuperMartijn642** [comment]
I think you created an issue on the wrong repository 🤔

**Comment by OliverWolf621** [comment]
whoops. sorry. im tired :(
