### ISSUE TITLE
[Crash] Crash with Fusion Enabled as a Required Dependency for Re-chiseled; Java Runtime Env.

### ISSUE THREAD

**Issue by FocalFlare** [SuperMartijn642/Fusion#2]
_Out of every crash I've gotten, whether it is an infinite ticking loop crash, rendering screen crash, hard and abrupt crash (log ends with "Process exited with code x"), a mod dependency crash (missing mods which will be stated in each log if they aren't enabled), or a crash regarding a mod interference, this crash seems rare to me and it only seems to happen with Re-chiseled and Fusion enabled._

_Solutions for this crash might work for everyone who's having this same issue but are 100% not guaranteed to work for those with even a slightly different issue. Regardless, I appreciate your input(s)!_

**Version Info**
- Minecraft **1.18.2**
- Re-chiseled **1.1.0** [Forge]
- Fusion **1.0.0** [Forge]
- Forge **40.2.9**

**Steps to Reproduce**
1. Update Re-chiseled to 1.1.0, which now requires **Fusion**.
2. Try to launch the game [ends with a dependency crash due to **Fusion** not being present].
3. Enable both **Re-chiseled** and download the new required dependency **Fusion** [ends with a JRE crash].

**Crash report (~/logs/latest.log)**
(hs_err_pidxxxxx.log is provided below as Java/Eclipse made a log for this crash.)
[hs_err_pid17600.log](https://github.com/SuperMartijn642/Fusion/files/11797177/hs_err_pid17600.log)
[latest.log](https://github.com/SuperMartijn642/Fusion/files/11797179/latest.log)

**Comment by FocalFlare** [comment]
_Before anyone says, I did look at someone's issue [#1] where their game was prevented from launching with **Oh The Biomes You'll Go** enabled, but I did not see any instance of a fatal Java runtime error in the log. If needed, I can open this issue in Re-chiseled!_

**Comment by SuperMartijn642** [comment]
The game seems to start fine with Rechiseled and Fusion installed.

Are you using any other mods? If so, could you narrow down the mods needed to reproduce the issue?

**Comment by SuperMartijn642** [comment]
If you were using Oculus/Iris, version 1.0.0a of Fusion might fix the issue.

**Comment by FocalFlare** [comment]
> If you were using Oculus/Iris, version 1.0.0a of Fusion might fix the issue.

_I'll try this out later._ 👍🏾

**Comment by FocalFlare** [comment]
> The game seems to start fine with Rechiseled and Fusion installed.
> 
> Are you using any other mods? If so, could you narrow down the mods needed to reproduce the issue?

_I am using mods, yes, but even so, Re-chiseled worked completely fine without Fusion before 1.1.0. This may be tedious for me, but I could still try this out._

**Comment by FocalFlare** [comment]
_Seems that this version of Fusion with the current latest version of Re-chiseled fixed this issue._
