### ISSUE TITLE
[Question] I can´t use the mod Rechiseled in aternos.

### ISSUE THREAD

**Issue by LuisDaAS** [SuperMartijn642/Fusion#20]
**Question**
I put the mod, and the 2 dependences but when I open Minecraft it says that I have to install the mod Fusion... but there´s not a version of the mod for Forge. What can I do?

**Comment by SuperMartijn642** [comment]
Fusion is available for both Forge and Fabric.

**Comment by LuisDaAS** [comment]
> Fusion is available for both Forge and Fabric.

Where can I find it? I try search here for 1.20.1 but I don't see it: https://legacy.curseforge.com/minecraft/mc-mods/fusion-connected-textures/files/4771503

**Comment by SuperMartijn642** [comment]
For the legacy site, when you click on the 'files' tab, it only shows a couple versions. Fusion is available for far more versions then the number of file it shows. To view them all, you have to press the 'View All' button.
Then simple look for Forge and 1.20.1 in the list:
![image](https://github.com/SuperMartijn642/Fusion/assets/12382965/61539ef2-32fb-47e6-9032-49a2fdc99868)

Alternatively, you can use the new site. The new site has filters for both the mod loader and Minecraft version. You can simply select Forge and 1.20.1, and it'll shows all files for that version:
![image](https://github.com/SuperMartijn642/Fusion/assets/12382965/425260e1-b583-46d7-856b-a3c72c537f59)

**Comment by LuisDaAS** [comment]
Ohh sorry, I don´t see that. Thank u man, I appreciate it!
