### ISSUE TITLE
[Bug] ... id guess its a butg or i did forget something

### ISSUE THREAD

**Issue by gamingoninsulin** [SuperMartijn642/Fusion#21]
**Version Info**
- Minecraft, 1.20.1
- Fusion, 1.0.6

**Are you using OptiFine:**  no

**Description of the Bug**
i am making in a mod for minecraft 1.20.1 that adds connecterd textures but evry time i load my mod with this a mod i the test face is giving me an error 

ERROR: Could not find maven.modrinth:fusion-connected-textures:1.0.6-mc1.20.1_mapped_parchment_2023.06.26-1.20.1.
is it because i use parchment mappings ?

**Steps to Reproduce**
make a blank mod add the parchment mappings 1.20.1 and add your mod 

like so:

in the build.gradle

```
repositories {
  exclusiveContent {
          forRepository {
              maven {
                  name = "Modrinth"
                  url = "https://api.modrinth.com/maven"
              }
          }
          forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
          filter {
              includeGroup "maven.modrinth"
          }
      }
   }

dependencies {
   implementation fg.deobf("maven.modrinth:fusion-connected-textures:${fusion_version}-mc${minecraft_version}")
}
```

gradle.properties:

```
# fusion version
fusion_version=1.0.6

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
```

**Screenshots**
![help wanted](https://github.com/SuperMartijn642/Fusion/assets/59486309/5c602cf8-1436-4acc-bac6-d41278cb1c40)

ps if you need any more information i am happy to help.
i hope hear from you ;)

**Comment by SuperMartijn642** [comment]
Ah it should be `"maven.modrinth:fusion-connected-textures:<fusion-version>-forge-mc<minecraft-version>"` (The '-forge-' part specifically). I have also updated the wiki now to include 'forge'/'fabric'.

**Comment by gamingoninsulin** [comment]
<3 thanks its working like a charm again ;)
