### ISSUE TITLE
[Crash] mixin crash [fusion.mixins.json:BlockModelMixin] 1.20.1 forge

### ISSUE THREAD

**Issue by gamingoninsulin** [SuperMartijn642/Fusion#22]
**Version Info**
- Minecraft, 1.20.1
- Fusion, 1.0.6

**Are you using OptiFine:** no

**Steps to Reproduce**
install a blank mod with not blocks and items.
when i load my mod along side fusion trough intlij it gives [fusion.mixins.json:BlockModelMixin] error

**Crash report (~/logs/latest.log)**
[crash-2023-10-30_21.18.59-client.txt](https://github.com/SuperMartijn642/Fusion/files/13209601/crash-2023-10-30_21.18.59-client.txt)

ps i do not know whats going on or what i did wrong

i did the correct gradle build and propperties and have this in mods.toml
mods.toml
```
[[dependencies.${mod_id}]]
    modId="fusion"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"
```
build.gradle
```
repositories {
   exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
}
dependencies {
        implementation fg.deobf("maven.modrinth:fusion-connected-textures:${fusion_version}-forge-mc${minecraft_version}")

}
```
gradle.propperties

```
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# fusion version
fusion_version=1.0.6

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.2.1
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)

# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=parchment
mappings=1.20.1-2023.06.26-1.20.1

## Mod Properties
mod_id=factoryblocks
mod_name=Factory Blocks Mod
mod_license=MIT
mod_version=1.0-1.20.1
mod_group_id=me.gamingoninsulin.factoryblocksmod
mod_authors=GamingOnInsulin
mod_description=This mod adds Factory blocks to minecraft.
```
everything else is template blank forge 1.20.1 mod

i hope you can see what i am doing wrong ( a moment ago i tought it was working clearly not)

**Comment by SuperMartijn642** [comment]
In order to use mods with mixins in dev, you'll have to setup the MixinGradle plugin. You can find instructions on how to set up MixinGradle with Forge here https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge.
In case you don't need to use mixins yourself and just want to load Fusion, just doing step 1 should be sufficient.

**Comment by gamingoninsulin** [comment]
your my hero ;)
