### ISSUE TITLE
[Question]  how to cutsom textures work i dont understand

### ISSUE THREAD

**Issue by gamingoninsulin** [SuperMartijn642/Fusion#23]
**Question**
i have datagenerators but i dont know how the add the datagenrators form your mod and also its not clear where to put the the images for simple layout and aslo the full layout 
can you help me with that 

i use 1.20.1 minecraft 
and 1.0.6 of fusion

when i run data gen in intelij non fusion files or additions are added do i need to call the fusion Model Provider somewhere

**Comment by SuperMartijn642** [comment]
You can add the datagenerators just like you would regular datagenerators, for example like with vanilla recipes or block models.

> also its not clear where to put the the images for simple layout and aslo the full layout

You just put them in your resources like regular textures 🤔

> when i run data gen in intelij non fusion files or additions are added do i need to call the fusion Model Provider somewhere

I have no clue what that sentence means

**Comment by gamingoninsulin** [comment]
Oh silly me i was forgetting to add the file to my data generators 

And its working now (half) the textures are not connecting i added all the file the data generator made json files for my block 02 to 15 (i made a typo while editing images o forgot 01 and 00 is my default image)

Maybe i chaged thing arround:

I got this 

```
class MyModsModelProvider extends FusionModelProvider {
   ...
   @Override
   protected void generate() {
      var modelData = ConnectingModelDataBuilder.builder()
            .parent(new ResourceLocation("minecraft", "block/cube_all"))
            .texture("all", new ResourceLocation("mymod", "block/oak_tiles"))
            .connection(DefaultConnectionPredicates.isSameBlock())
            .build();
      var modelInstance = ModelInstance.of(DefaultModelTypes.CONNECTING, modelData);
      this.addModel(new ResourceLocation("mymod", "block/oak_tiles"), modelInstance);// <- i duplicated this line a couple of times
   }
}
```

If i am right .texture "all" is the default texture right  or how shoud i read this?

**Comment by gamingoninsulin** [comment]
i did found out what i was missing by lokking at other issues and this one helped me you siad to him/her that ther was a texturepack  and i found out that i was missing <blockname>.png.mcmeta file now its working like a charm and i had all the images seperate and needed to be 1 image multiple bombination woops 

i checked this issue (it has notting to do wtih this btw) [Question] Fusion ignores Forge's render_type model property
and you said someting about transparant texutres and gave this link this was my solution.
the link  [thextuepack link he quoted](https://www.curseforge.com/minecraft/texture-packs/mt-ct-d)


as for this 

> when i run data gen in intelij non fusion files or additions are added do i need to call the fusion Model Provider somewhere

i was trying to explain that at that time no files where generated for fusion (example the models) and did found out later to call it in my DataGeneratior class with (packedOutput)  non the less its woking 100% 

btw thank you for your time 
kind regard GamingOnInsulin (aka Jordy)
