### ISSUE TITLE
[Feature] Missing the green library badge in modmenu

### ISSUE THREAD

**Issue by nco2k** [SuperMartijn642/Fusion#24]
can you please modify the mod so that it gets properly recognized as a library by modmenu, and therefor doesnt show up by default?

apis like fabric, cloth, yacl etc. have a green library badge in modmenu, and only show up if you toggle the button from "Libraries: Hidden" to "Libraries: Shown". i would appreciate it if this library behaved the same.

**Comment by SuperMartijn642** [comment]
Added now in Fusion version 1.1.0a.
