### ISSUE TITLE
Crash when enable connected textures in rechiseled

### ISSUE THREAD

**Issue by lostopkk** [SuperMartijn642/Fusion#25]
https://mclo.gs/EwJLxjq

**Comment by djnifos** [comment]
Same with forge [https://mclo.gs/ZS4lJjj](https://mclo.gs/ZS4lJjj)

**Comment by SuperMartijn642** [comment]
> Same with forge https://mclo.gs/ZS4lJjj

That is a completely different error.

Both are fixed now in Fusion version 1.1.0a.
Thank you for reporting the issue!
