### ISSUE TITLE
[Crash] When hitting rechisel blocks with connected texture

### ISSUE THREAD

**Issue by KayZiomalek** [SuperMartijn642/Fusion#27]
Version Info
- Minecraft, 1.20.1
- Fusion, 1.1.0

No Optifine

Steps to Reproduce
Just what the tittle says hit a block from rechisel with connected texture

Crash report 
[crash-2023-11-12_01.22.48-client.txt](https://github.com/SuperMartijn642/Fusion/files/13326845/crash-2023-11-12_01.22.48-client.txt)

**Comment by SuperMartijn642** [comment]
Fixed now in Fusion version 1.1.0a.
Thank you for reporting the issue!
