### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by 800020h** [SuperMartijn642/Fusion#28]
**Version Info**
- Minecraft, 1.19.2
- Fusion, 1.1.0
- fabric, 0.14.23
- fabric API, 0.76.1+1.19.2
- sodium, 0.4.4+build.18
- indium, 1.0.9+mc1.19.2

**Are you using OptiFine:** Yes or no
no

**Description of the Bug**
some sub chunks (the ones with rechiseled connected textures blocks in them) were invisible
when I placed a block in one it crashed

**Steps to Reproduce**
it happened when I updated from fusion 1.0.6
the blocks were already placed
it is possible some mods were involved that aren't listed in "version info"

**Screenshots**
I didn't think to take any

**crash report**
https://gist.github.com/800020h/1951482df3a9fa7d5f3fb46e3ccd42e6

**Comment by SuperMartijn642** [comment]
Fixed now in Fusion version 1.1.0a.
Thank you for reporting the issue!
