### ISSUE TITLE
[Question] Incompatible with Continuity(fabric)?

### ISSUE THREAD

**Issue by lostopkk** [SuperMartijn642/Fusion#3]
**Question**
...Incompatible with Continuity(fabric)?

**Comment by SuperMartijn642** [comment]
Fusion has nothing to do with Continuity. Not sure why it'd be incompatible.

**Comment by Fleepe** [comment]
@SuperMartijn642 I initially thought that both mods do the same thing, but now, after your answer, I can’t understand at all what the differences are between these two mods.
