### ISSUE TITLE
[Question] Fusion server support

### ISSUE THREAD

**Issue by titouanlacombe** [SuperMartijn642/Fusion#32]
I want to add the connected glass mod to my server.

Since fusion is marked as unsupported on the server (in the .mrpack), the server doesn't download the lib and it crashes because connected glass requires fusion.

Am I doing something wrong? I'll just downgrade the connected glass version for now.

**Comment by SuperMartijn642** [comment]
> For now, I'll just downgrade the connected textures version.

Wut, what do you mean by that? Connected textures is a concept.

> I want to add connected textures to my server.

The server doesn't have any textures 🤔

**Comment by titouanlacombe** [comment]
Sorry, I meant connected glass

**Comment by SuperMartijn642** [comment]
Ah I see, Fabric has no way to mark a dependency for only the client, hence it's either no dependency or a dependency on both the server and the client.

Fusion does nothing on a server which why it is marked as client only on Modrinth, however you can still install it just fine.
