### ISSUE TITLE
[Feature] Example Texture Pack

### ISSUE THREAD

**Issue by FalconinVoid** [SuperMartijn642/Fusion#34]
Please make an example resourcepack, the folder structure is very unclear in the Wiki.

**Comment by SuperMartijn642** [comment]
The folder structure is just the same as vanilla.

**Comment by FalconinVoid** [comment]
The problem is more that I have no idea where I have to make the files and stuff, a example resource pack would really help to understand the folder and file structure. It would make the possibilities more clear too.

**Comment by SuperMartijn642** [comment]
> The problem is more that I have no idea where I have to make the files and stuff, a example resource pack would really help to understand the folder and file structure.

Fusion does not change where you'd have to put the files. It's just the same as a regular resource pack.
There's plenty of examples for resource packs out there.

Still I can probably create a repository for a resource pack which contains everything mentioned on the wiki.

**Comment by FalconinVoid** [comment]
When is the resource pack released? I am really trying to understand, but some arguments are just out of my understanding. I am just getting this texture. https://media.essential.gg/4c63f970-4364-4d33-36aa-ee85a50c7400
A resourcepack with every possibility would be really helpful!

**Comment by SuperMartijn642** [comment]
Did you add the .mcmeta file for your texture?

**Comment by FalconinVoid** [comment]
Yes I added a mcmeta file:
{
   "fusion": {
      "type": "connecting",
      "layout": "full",
      "render_type": "cutout"
   }
}

**Comment by SuperMartijn642** [comment]
Make sure the location for that file is correct. If you a file `planks.png`, that file should be `planks.png.mcmeta`.

**Comment by FalconinVoid** [comment]
Okay. I also noticed, that I have the .json file only in the models, not in the models/block. I'll retry.

**Comment by FalconinVoid** [comment]
It worked! Thank you for your help! I'm just having some texturing issues now, but I can fix them on my own.

**Comment by FalconinVoid** [comment]
Okay I'm having another issue. I am trying to make block overlays, but it doesn't work. I have checked the folder structure and have copied the data from the wiki. What am I doing wrong? (Picture of the gravel: https://media.essential.gg/565c837a-6819-4830-5998-118b2d0bc400)

**Comment by SuperMartijn642** [comment]
I can't tell what is wrong from just an ingame screenshot. Please share the relevant files.

**Comment by FalconinVoid** [comment]
Yeah sure! Here:

[Fusion.zip](https://github.com/SuperMartijn642/Fusion/files/13601748/Fusion.zip) (That's the resourcepack)

**Comment by SuperMartijn642** [comment]
You need to add the `example:sand_overlay` texture to the block atlas. Any texture in the `block` folder will automatically be added to the block atlas. For textures outside the `block` folder, you'll have to add it to the block atlas yourself if you want to use the texture on a block. This is done through the atlas source files.
https://minecraft.wiki/w/Resource_pack#Atlases

**Comment by FalconinVoid** [comment]
I honestly don't know how to do that. The wiki says the path is relative to the textures folder, so how do I add textures outside of "minecraft/textures"?

**Comment by FalconinVoid** [comment]
Could you give me the file required to add the texture so I can understand it?

**Comment by SuperMartijn642** [comment]
Simplest option is to just move the `example:sand_overlay` texture into the `block` folder.

The other option is to add it to the block atlas through the atlas source file. This is done by creating a `assets/minecraft/atlases/blocks.json` file with the following content:
```json
{
   "sources": [
      {
         "type": "single",
         "resource": "example:sand_overlay"
      }
   ]
}
```

Everything you have asked so far is just vanilla resource pack stuff and unrelated to Fusion. For examples, you can probably look into other resource packs, the Minecraft wiki, or texture pack tutorials.
There's also this resource pack on CurseForge which uses Fusion, which might also help as an example: https://www.curseforge.com/minecraft/texture-packs/mt-ct-d

**Comment by FalconinVoid** [comment]
I've never changed any models until now, but thank u for helping me. (That's the reason why I wanted an example resource pack. I learn by exploring)
