### ISSUE TITLE
Incompatibility with Fusion By skrallexy

### ISSUE THREAD

**Issue by MecVans** [SuperMartijn642/Fusion#36]
1.18.2
Java Version
Fusion 1.1.0 for Forge 1.18

I'm not using optfine

This mod doesn't work when you have SimpleOres:Fusion (On curseforge it's just "Fusion"), it just doesn't work, I sent a bug report to them, and the answer was "The problem is that their mod is using the same mod id as mine: "fusion". I cannot retroactively change what is already out there, though I can change it for 1.20.2, since I haven't ported to it yet. The problem with backporting a name change is that I would have to change every single simpleores mod that uses "Fusion Furnace" alloys, (and thus refers to fusion:fusion_furnace) and that's all but two of them."
...

Being honest, I downloaded Rechiseled and at first I din't notice there was a dependency, then Minecraft reported me I'd need Fusion, I searched on CurseForge and downloaded the first I saw, and it was SimpleOres:Fusion, I haven't noticed it wasn't the right mod and minecraft started fine after installing it, so, I thought I was good, but in game the textures of some chiseled blocks weren't connecting,  so I decided to go back to the page and then I noticed that I had downloaded the wrong "fusion", so I downloaded the right but the textures continued not connecting, and when I searched for "fusion" on the list of mods in-game, there was just "Fusion (SimpleOres:Fusion)", removing this mod, the textures work properly. It's like they're the same mod.

Are there something I (or you) could do?

**Comment by SuperMartijn642** [comment]
> the textures continued not connecting, and when I searched for "fusion" on the list of mods in-game, there was just "Fusion (SimpleOres:Fusion)"

Forge simply sees two jars with mods with the same modid and assumed it's the same mod. Whenever there's multiple jars for the same mod, Forge will just load the newest one and since SimpleOres:Fusion has a higher version number the other one does not get loaded.

Nothing that can really be done about this. It's just unfortunate that both mods happen to have the same modid.

**Comment by MecVans** [comment]
So yeah, that's it...

Well, at least now you know. If you or him change it in newer versions other people won't face it.

Thank you, anyway.
