### ISSUE TITLE
[Question] Does Fusion work with packs made for OptiFine?

### ISSUE THREAD

**Issue by mimi-min** [SuperMartijn642/Fusion#38]
**Question**
I tried your mod with a resource pack that's supposed to have connected textures, but it didn't work. 

Then I saw a closed issue in which you stated you won't make the mod compatible with OptiFine's format for connected textures.

Does that mean that resource packs made for OptiFine simply won't work with this mod?

Is there some easy way we can convert them? (I have friends who aren't comfortable with technology)

I'm just trying to find some way we can use connecting texture packs without too much trouble...

**Comment by SuperMartijn642** [comment]
> Does that mean that resource packs made for OptiFine simply won't work with this mod?

Indeed, it won't work with Fusion as it's well, 'made for OptiFine'.

> Is there some easy way we can convert them?

Nope, sadly not, the formats are quite different.
