### ISSUE TITLE
[Question] How to apply tint to texture

### ISSUE THREAD

**Issue by stalker57241** [SuperMartijn642/Fusion#39]
**Question**
I tried everything, but don't understand, how to apply change of tintindex in texture. I put it on overlay, the file become like this:
```Java
// It is gravel.json
{
	"loader": "fusion:model",
	"type": "connecting",
	"parent": "minecraft:block/block",
	"textures": {
		"particle": "#all",
		"all": "minecraft:block/gravel",
		"grass_overlay": "default_overlays:overlays/grass_overlay"
	},
	"connections": {
		"grass_overlay": [
			{
				"type": "match_block",
				"block": "minecraft:grass",
				"tintindex": 0
			}
		]
	},
	"elements": [
		{
			"from": [0, 0, 0],
			"to": [16, 16, 16],
			"faces": {
				"down":  { "texture": "#all", "cullface": "down" },
				"up":   { "texture": "#all", "cullface": "up" },
				"north": { "texture": "#all", "cullface": "north" },
				"south": { "texture": "#all", "cullface": "south" },
				"west":  { "texture": "#all", "cullface": "west" },
				"east":  { "texture": "#all", "cullface": "east" }
			}
		},
		{	"from": [ 0, 16, 0 ],
			"to": [ 16, 16, 16 ],
			"faces": {
				"up": { "texture": "#grass_overlay", "cullface": "up", "tintindex": 0 } // yes, "tintindex": 0
			}
		}
	],
	"credit": "Stalker57241"
}
```
`grassoverlay.png`
![screenshot111](https://github.com/SuperMartijn642/Fusion/assets/40300537/852ac286-7a8b-4e07-97e1-b5b085590968)
`grassoverlay.png`
```Java
// grass_overlay.png.mcmeta
{
	"fusion": {
		"type": "connecting",
		"layout": "full",
		"render_type": "cutout"
	}
}
```

But it not changed form to look like full bitmap I used, and not got color of biome (It's primary problem. First mentioned problem I saw when closely looked at block).
![2023-12-16_22 19 17](https://github.com/SuperMartijn642/Fusion/assets/40300537/9000d12d-d808-4d15-ab57-4a7b3ebf7702)

**Comment by SuperMartijn642** [comment]
> I tried everything, but don't understand, how to apply change of tintindex in texture

Wut, that is not something you can do. You can't just randomly put it in the connections 🤔

Block tinting is hardcoded per block. Fusion does not add anything for block tinting.
