### ISSUE TITLE
[Crash] Crash while loading

### ISSUE THREAD

**Issue by Sixdd6** [SuperMartijn642/Fusion#4]
**Version Info**
- Minecraft, 1.12.2 Forge 14.23.5.2860
- Rechiseled, 1.1.0
- Fusion, 1.0.0

**Steps to Reproduce**
Start Minecraft, crash while loading

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Fusion/files/11807770/latest.log)
[crash-2023-06-20_16.40.50-client.txt](https://github.com/SuperMartijn642/Fusion/files/11807772/crash-2023-06-20_16.40.50-client.txt)

**Comment by SuperMartijn642** [comment]
It works fine with just Fusion installed.
You are using a lot of other mods, please narrow down the mods needed to reproduce the issue.
