### ISSUE TITLE
[Question] Can I target a block more than once for overlays?

### ISSUE THREAD

**Issue by ZeroLevels** [SuperMartijn642/Fusion#42]
**Question**
My resource pack that I made for Optifine (ZLTweaks) has grass overlays to other blocks. This isn't special, but I also have a second overlay for the block the grass is spreading to in order to add a sort of shaded edge around the grass, making it look like there's some depth.

These are some old examples, but they show it off well enough for this question.
![1_grass_after_10x](https://github.com/SuperMartijn642/Fusion/assets/3106890/cbe1d12e-1fd1-4f2a-b505-1c3d49dd3403)
![grass_overgrowth](https://github.com/SuperMartijn642/Fusion/assets/3106890/69ed731b-fb22-4ed2-9bb9-04eb8b2ba763)

The only reason a second overlay was required is because I needed the initial grass texture to maintain its biome-coloring, and then the shadowing needed to just be a standard, unshaded texture. Can I achieve a similar effect with fusion? It's the only reason in any/all iterations of non-Optifine CTM that I haven't switched over.

**Comment by SuperMartijn642** [comment]
There's nothing preventing you from having multiple connected textures in a model, thus you can indeed have multiple overlays.
In vanilla, tinting of textures is hardcoded per block and Fusion currently does not have a way to change the tinting of a texture.
