### ISSUE TITLE
[Crash] Cannot start the game

### ISSUE THREAD

**Issue by TobiasReindl** [SuperMartijn642/Fusion#44]
**Version Info**
- Minecraft, 1.20.4
- Fusion, 1.1.0d

**Are you using OptiFine:** No, but Iris

**Steps to Reproduce**
This is the same issue as the one for Rechiseled, but I thought I try to post this twice so maybe anyone will see this:
https://github.com/SuperMartijn642/Rechiseled/issues/84
Was using Continuity for connected textures before and want to add Rechiseled so I also had to download Fusion.
Wanted to open up the game and it crashes. I also tried to disable the "Eating Animations Mod".
Dont really know what else I can do now. Also tried to disable Rechiseled so that I only launch it with Fusion. Same crash there so it also has to do something with Fusion (I guess).

**Crash report (~/logs/latest.log)**
First:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'eatinganimationid'!"

After disabling Eating Animations:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.resource.loader.ModNioResourcePack failed"

**Comment by SuperMartijn642** [comment]
This works fine with just Fusion and Rechiseled. Please narrow down what other mods are needed to reproduce the issue.

**Comment by ForkLiftInspector26** [comment]
I am also encountering a crash while launching Minecraft. It seems to only crash when I have Sodium installed.

**Comment by ForkLiftInspector26** [comment]
I am also encountering a crash while launching Minecraft. It seems to only crash when I have Sodium installed even while having Indium.

**Comment by ForkLiftInspector26** [comment]
Minecraft, 1.20.4
Fusion, 1.1.0d

I am also encountering a crash while launching Minecraft. It seems to only crash when I have Sodium installed even while having Indium.

**Comment by UltimatChamp** [comment]
Yes, I also encounter a crash with the following mods on 1.20.4:
- Fusion 1.1.0d
- Sodium 0.5.8
- Indium 1.0.30
