### ISSUE TITLE
[Feature] BlueMap compatibility / integration.

### ISSUE THREAD

**Issue by materusPL** [SuperMartijn642/Fusion#45]
**Is your feature request related to a problem? Please describe.**
Currently bluemap rendering of blocks using this library is broken as in screenshot.
![image](https://github.com/SuperMartijn642/Fusion/assets/28183516/3077404e-2185-46e9-ba71-2247c5c1661d)
I guess it's caused by how textures are mapped to blocks.

**Describe the solution you'd like**
Generate standard single block / non connecting texture for compatibility with bluemap or some other way to make bluemap render correctly.

**Comment by SuperMartijn642** [comment]
There is nothing I can do about this on my end. BlueMap is either loaded server-side or just from a save file in a website. In the first case, BlueMap just looks through resource packs manually as the server doesn't have anything texture related, thus there's nothing I can do. In the second case, mods aren't even involved.

You should probably request this on their side, as it stands they don't really have anything for mods to change what textures they use for blocks.
