### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by ArchieNemsesis** [SuperMartijn642/Fusion#46]
**Version Info**
- Minecraft, 1.20.4
- Fusion, 1.1.0c-fabric-mc1.20.4.jar

**Are you using OptiFine:**  Yes or No
No

**Steps to Reproduce**
Launch modpack

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Fusion/files/14233906/latest.log)

**Comment by SuperMartijn642** [comment]
This has already been fixed. Please update Fusion.
