### ISSUE TITLE
Incompatible with Optifine?  I get a crash when using both together

### ISSUE THREAD

**Issue by gwynhefar** [SuperMartijn642/Fusion#48]
**Version Info**
- Minecraft 1.12.2
- Fusion 1.1.0

**Are you using OptiFine:** Yes Optifine 1.12.2 HD_U_G5

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
...
---- Minecraft Crash Report ----
https://docs.google.com/document/d/1acUXplqcTqd30Wwr2gcF2KM75MsLvy56f7hIC9h6f4g/edit?usp=sharing

**Comment by SuperMartijn642** [comment]
Yup this is caused by OptiFine. Nothing I can do about this as OptiFine is closed source, so I can't know what they're changing.
