### ISSUE TITLE
[Feature] CTM Block overlay

### ISSUE THREAD

**Issue by Foreck1** [SuperMartijn642/Fusion#5]
**Is your feature request related to a problem? Please describe.**
There's a lack of mods that can emulate one of Optifine's more advanced features, block overlays that extend from (A) blocks to (B) blocks (detailed [here](https://optifine.readthedocs.io/ctm.html#general-properties)).

**Describe the solution you'd like**
It would be ideal to have a mod that can emulate most of MCpatcher's features outside of Optifine which is known to cause compatibility issues due to its other features. Being that CTM alternatives exist already, but features like CIT (custom item textures)
 and **CTM-overlays** do not, it would be ideal to see that feature.

Great mod btw. Cute and clean presentation.

**Comment by SuperMartijn642** [comment]
Is there an explanation of what `overlay` actually does somewhere? I am not familiar with it and the only thing on that page is this:
![image](https://github.com/SuperMartijn642/Fusion/assets/12382965/4ed792e5-f3eb-4206-8261-5a6e7f941968)

**Comment by Foreck1** [comment]
It makes a block draw a texture on surrounding blocks if they are specified. In this picture, grass is adding an overlay over red sand 
![image](https://github.com/SuperMartijn642/Fusion/assets/47757429/7e917626-e8b4-4c49-8759-1c5ccb426684)

Here's a personal example of how a functional implementation looks [RotN repo](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/tree/master/resourcepacks/Official%20ROTN%20tweaks/assets/minecraft/mcpatcher/ctm/grass_top)
And here's the template used by Optifine [optifine documenttion](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/images/overlay_template.png)

**Comment by Steamoonkie** [comment]
Sir?
https://legacy.curseforge.com/minecraft/mc-mods/connectedness

**Comment by SuperMartijn642** [comment]
In Fusion version 1.1.0 I now added the ability for connecting textures to override their render type. With that addition it is now possible to create block overlays using Fusion's existing connecting model and connecting textures.
I added a page on the wiki as to how to set it all up here: https://github.com/SuperMartijn642/Fusion/wiki/Block-Overlay-Example

Thank you for the suggestion!
