### ISSUE TITLE
[Bug] [Feature] Compatibility with Fusion furnace mod

### ISSUE THREAD

**Issue by rubi13rubi** [SuperMartijn642/Fusion#51]
In you try to use this mod with the fusion furnace mod it doesn't work. This bug is already documented in the other mod issues page:
https://github.com/Sinhika/Fusion/issues/19
The dev explains that it is caused by both mods having the same id "fusion". Is there a posibility for an update changing the mod id for compatibility?

**Comment by SuperMartijn642** [comment]
> Is there a posibility for an update changing the mod id for compatibility?

No, sadly not. You can't easily change a mod's modid retroactively. In the case of Fusion, changing the modid would break any existing resource packs made for fusion as well as any mods depending on Fusion.
Also #36 for reference.

**Comment by rubi13rubi** [comment]
Can't you just make a special version for compatibility with the other fusion mod? I don't wanna use resource packs, just the default mod for rechiseled, and I think changing this is easier than the other as the other mod is the base for a lot of mods that depend on it.

**Comment by SuperMartijn642** [comment]
> Can't you just make a special version for compatibility with the other fusion mod?

No, changing the modid would still break any resourcepacks as well as mod dependencies. This means all of Rechiseled's textures would be broken as well as the dependency on Fusion.
I am not gonna maintain two versions for all branches of Fusion and Rechiseled (or any of the other mods which use Fusion for that matter).

**Comment by rubi13rubi** [comment]
Understandable, thank you for replying.
