### ISSUE TITLE
[Bug] Wiki page example has json errors

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/Fusion#53]
**Description of the Bug**
This [wiki page](https://github.com/SuperMartijn642/Fusion/wiki/Default-Model-Types#connections-per-texture)'s example has json errors when placed in a json file. Because of this, I am unsure of the format to use when defining multiple textures.

**Steps to Reproduce**
1. Visit https://jsonlint.com/
2. Input example into text box.

**Screenshots**
![image](https://github.com/SuperMartijn642/Fusion/assets/12000593/3e80c593-63d4-41b1-b0bc-d067a3d8a1d1)

**Comment by SuperMartijn642** [comment]
Updated 👍

**Comment by WenXin20** [comment]
Thanks!
I am trying to get this working, but it is giving me an error. Is this not what it has?
**`Match block predicate must have string property 'block'!`**
```	"type": "connecting",
	"connections": {
		"side": {
			"type": "match_state",
			"block": "warp_pipes:clear_warp_pipe",
			"properties": "entrance"
		},
		"default": {
			"type": "is_same_block"
		}
	}
```

**Comment by SuperMartijn642** [comment]
Might be me copy-pasting and forgetting to change the error message.
What's wrong here, is that `properties` should be an object.
For example:
```yaml
...
"properties": {
  "waterlogged": "true"
}
...
```

**Comment by WenXin20** [comment]
Ah thanks, it is rendering now, although the textures are not connecting even though the state `entrance` is `true` for both blocks next to each other. Any idea why?  The block does have multiple blockstates though.
```
	"connections": {
		"side": {
			"type": "match_state",
			"block": "warp_pipes:clear_warp_pipe",
			"properties": { "entrance": "true" }
		},
		"default": { "type": "is_same_block" }
	},
```
[clear_warp_pipe_entrance_ns.json](https://github.com/SuperMartijn642/Fusion/files/14442411/clear_warp_pipe_entrance_ns.json)

**Comment by WenXin20** [comment]
I got it working, just had to list out all the states
