### ISSUE TITLE
[1.20.1] Connected Glass Textures Not Working

### ISSUE THREAD

**Issue by Flexico** [SuperMartijn642/Fusion#55]
**Question**
...
I'm converting my CTM for glass blocks to the Fusion format, but every glass block shows the upper-left option no matter what. What am I doing wrong?
[CTM Fusion Glass.zip](https://github.com/SuperMartijn642/Fusion/files/14681127/CTM.Fusion.Glass.zip)

**Comment by SuperMartijn642** [comment]
Connecting textures need to be used in conjunction with the connecting model type https://github.com/SuperMartijn642/Fusion/wiki/Default-Model-Types#connecting-models

**Comment by Flexico** [comment]
Ah, I see! Ok, I have the following at /models/block/glass.json:
```
{
	"loader": "fusion:model",
	"type": "connecting",
	"connections": [
		{ "type": "is_same_block" }
	],
	"parent": "block/cube_all",
	"textures": { "all": "block/glass" }
}
```
![2024-03-21_02 40 34](https://github.com/SuperMartijn642/Fusion/assets/5751770/654da88a-121b-4a72-ad3b-28befc35d6e1)
![2024-03-21_02 41 09](https://github.com/SuperMartijn642/Fusion/assets/5751770/8ee5ee34-163f-4fe6-b0e6-8efc5aa606d3)

It does affect which textures show on the blocks, but they are mostly the wrong ones!

**Comment by Naixatloz** [comment]
It doesn't look like they're placed correctly on the template. This is what mine is laid out like, for reference, and everything looks correct.
![glass](https://github.com/SuperMartijn642/Fusion/assets/92188768/5c0a1717-ca1a-4147-97d4-e5554f4e1ae2)

**Comment by Flexico** [comment]
Ah -- your setup looks different from the one I followed. I'll have to re-order them.

**Comment by Flexico** [comment]
It wooorrrks! Thanks for the help~
