### ISSUE TITLE
[Bug] Some mods that require fusion are not compatible with modernfix

### ISSUE THREAD

**Issue by oof100200** [SuperMartijn642/Fusion#56]
**Version Info**
- Minecraft, 1.20.1 forge - Fusion, 1.1.1

**Are you using OptiFine:** no

**Description of the Bug**
When I use a mod that requires fusion, the connection block doesn't work, when I remove modernfix, everything works fine.

**Steps to Reproduce**
https://modrinth.com/mod/dawn-of-time-builder-edition/version/1.5.3

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
This appears to have been fixed on ModernFix's end https://github.com/embeddedt/ModernFix/commit/c15b95e2be8467306e03f12d1638e840d10a6726.
Thank you for reporting the issue!
