### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by KaiKingStreams** [SuperMartijn642/Fusion#57]
**Version Info**
- Minecraft 1.20.1
- Fusion 1.1.1

**Are you using OptiFine:** No

**Description of the Bug**
For some reason, the mod isn't working at all.

**Steps to Reproduce**
N/A

**Screenshots**
...
![image](https://github.com/SuperMartijn642/Fusion/assets/59054276/d6d88517-8236-43a3-a8ec-5dbb535f0f49)

**Comment by SuperMartijn642** [comment]
Please explain what isn't working. Are you using a resource pack?

**Comment by KaiKingStreams** [comment]
> Please explain what isn't working. Are you using a resource pack?

No, I am not using a resource pack. Fusion is installed and I don't think other mods are interfering, here is the log if you wanna see.
[latest.log](https://github.com/SuperMartijn642/Fusion/files/14766088/latest.log)

**Comment by SuperMartijn642** [comment]
I don't think you understand what the mod does. Without a resource pack Fusion won't have any effect.

**Comment by KaiKingStreams** [comment]
> I don't think you understand what the mod does. Without a resource pack Fusion won't have any effect.

Where's the resource pack at than?

**Comment by SuperMartijn642** [comment]
Wut? Fusion just adds additional features which can be used by resource packs such as connected textures.

**Comment by KaiKingStreams** [comment]
Connected textures only has a resource pack for 1.12.2

**Comment by SuperMartijn642** [comment]
I have no clue what that message means

**Comment by KaiKingStreams** [comment]
> Wut? Fusion just adds additional features which can be used by resource packs such as connected textures.

i was replying to this

**Comment by SuperMartijn642** [comment]
Connected textures is a feature of Fusion, not a resource pack
