### ISSUE TITLE
[Crash] Exit Code 1 Crash during bootup/loading

### ISSUE THREAD

**Issue by Devilswarchild** [SuperMartijn642/Fusion#6]
**Version Info**
- Minecraft Version: 1.20.1
- Fusion (Connected Textures) Version: fusion-1.0.1-forge-mc1.18.jar
- Forge Version 47.0.15

**Steps to Reproduce**
Loaded it up in the latest version of my modpack (hasnt been released yet) and crashes during the boot up process i.e. the loading screen.

when I disable fusion the error stops happening,

**Crash report (~/logs/latest.log)**
...
[debug.log](https://github.com/SuperMartijn642/Fusion/files/11826808/debug.log)
[latest.log](https://github.com/SuperMartijn642/Fusion/files/11826809/latest.log)
[launcher_log.txt](https://github.com/SuperMartijn642/Fusion/files/11826811/launcher_log.txt)

![Screenshot_4](https://github.com/SuperMartijn642/Fusion/assets/27385258/c46fa4f2-6490-426c-8b6e-7037c19b7d34)

mods present in my modpack:

[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Fast Portals (by gluegunner4)](https://www.curseforge.com/minecraft/mc-mods/fast-portals)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Occultism (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/occultism)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[Armourer's Workshop (by RiskyKen)](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Erroring Entity Remover Reforged (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/erroring-entity-remover-reforged)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Creeper Firework (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/creeper-firework)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Rune Craft (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/rune-craft)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Epic Samurai's (by VeroxUniverse)](https://www.curseforge.com/minecraft/mc-mods/epic-samurais)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Tree Harvester (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[Bigger Stacks (by thanksihadtosignupforthis)](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks)
[Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/cha-s)
[Lithereal (by TheLightBlueGame)](https://www.curseforge.com/minecraft/mc-mods/lithereal)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Leaky[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/leaky)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[GravelMiner (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/gravelminer)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Neruina - Ticking Entity Fixer (by bawnorton)](https://www.curseforge.com/minecraft/mc-mods/neruina)
[Ambient Environment (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ambient-environment)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Variant Crafting Tables [Forge] (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Visual Overhaul (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Chunk Animator (by Lumien231)](https://www.curseforge.com/minecraft/mc-mods/chunk-animator)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)

**Comment by SuperMartijn642** [comment]
Same as for Rechiseled:
The `latest.log` doesn't show any error and appears to be cutoff. Are you sure that's the entire log?

That is quite a lot of mods, please narrow down the mods needed to reproduce the issue.

**Comment by Devilswarchild** [comment]
I assure you they are all necessary. Its a modpack of my creation up on
curseforge. MineColonies: Dimensional Adventure

**Comment by SuperMartijn642** [comment]
> I assure you they are all necessary.

Wut I am 100% certain you don't need all those mods to reproduce the issue 🤔

**Comment by Devilswarchild** [comment]
ok I ran it this time with just fusion, re-chiseled , jade and jei

[debug.log](https://github.com/SuperMartijn642/Fusion/files/11842261/debug.log)

[latest.log](https://github.com/SuperMartijn642/Fusion/files/11842262/latest.log)

[crash-2023-06-22_20.24.43-client.txt](https://github.com/SuperMartijn642/Fusion/files/11842266/crash-2023-06-22_20.24.43-client.txt)

[launcher_log.txt](https://github.com/SuperMartijn642/Fusion/files/11842267/launcher_log.txt)

**Comment by SuperMartijn642** [comment]
Thanks will have a look tomorrow

**Comment by SuperMartijn642** [comment]
> Mod §efusion§r requires §6minecraft§r §o1.18 or above, and below 1.19§r §7Currently, §6minecraft§r§7 is §o1.20.1

I think you might have the wrong version of Fusion installed, are you sure you have the correct version of Fusion?

**Comment by Devilswarchild** [comment]
Yes,  im sure its correct version

**Comment by SuperMartijn642** [comment]
Actually you also reported using version fusion-1.0.1-forge-mc1.18.jar for 1.18. But you're using Minecraft 1.20.1

**Comment by Devilswarchild** [comment]
bc that is what curseforge installed when i clicked install for 1.20.1

**Comment by Devilswarchild** [comment]
why is this closed as completed when you didnt even reply to my previous
comment?

**Comment by SuperMartijn642** [comment]
All files are marked correctly on CurseForge. You're using a the file for 1.18 on 1.20.1, nothing I can do about that 🤷‍♂️

**Comment by Devilswarchild** [comment]
yeah cause thats what got installed when browsing through add more content on my 1.20.1 instance on the curseforge app

**Comment by Devilswarchild** [comment]
but its fine, ive removed both fusion and re-chiseled since they were giving me the errors

**Comment by sandalle** [comment]
Weird, same issue here. CurseForge is installing https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures/files/4601383 (1.18 Fabric version) instead of a 1.20.1 Forge version. I believe this is because the only 1.20.1 version is for Fabric ( https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures/files/4601355 ) , but my client is set to Forge and that only has a 1.20 Forge version ( https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures/files/4601338 only lists 1.20, not 1.21 ), so this is confusing CurseForge. When I look at Versions for the installed Fusion (Connected Textures) mod, it actually shows no valid versions (including the one that they installed when I picked it from the Browse Mods list).

Issue appears to be:
* Using MC 1.20.1
* Fusion (Connected Textures) has a MC 1.20 + 1.20.1 version listed for Fabric
* Fusion (Connected Textures) only has a MC 1.20 (_not_ 1.20.1) version listed for Forge
* CurseForge sees that _a_ version of Fusion (Connected Textures) is available for MC 1.20.1, so then tries to install it, but as my client is set to Forge (not Fabric), it instead grabs the 1.18 Forge version (not sure why it doesn't grab the available 1.20 Forge version; possibly because the 1.18 version is listed first in the Files section).

**Comment by SuperMartijn642** [comment]
Thank you for the report, but not much I can do about this. Report it to CurseForge I guess 🤷‍♂️

**Comment by sandalle** [comment]
> Thank you for the report, but not much I can do about this. Report it to CurseForge I guess 🤷‍♂️

Can you upload a Forge version for MC 1.20.1 or mark the already uploaded MC 1.20 version for Forge as working with 1.21 as well (if it does)? I believe that’s the fix.

**Comment by SuperMartijn642** [comment]
I have already tried to a couple times, however CurseForge seems to just not update certain files when I make changes. If you want a better experience consider using Modrinth which now also has its own launcher.

**Comment by sandalle** [comment]
As of 2023/07/02 the fusion-1.0.2-forge-mc1.20.jar (and the 1.0.1 version) shows up for MC 1.20.1 modpacks in the Versions list for CurseForge and shows it was updated today, thanks!
