### ISSUE TITLE
[Bug] [Modrinth] ClassCastException on connecting model using `match_state` predicate

### ISSUE THREAD

**Issue by Davoleo** [SuperMartijn642/Fusion#65]
**Version Info**
- Minecraft 1.20.1
- Fusion 1.1.1

**Are you using OptiFine:** No

**Description of the Bug**
Fusion Connecting model `match_state` predicate exception during deserialization.
Error happens on the same line that was changed in this commit: https://github.com/SuperMartijn642/Fusion/commit/c5c3a28dd9e64012a23fb45653d9fc961d95e341
I checked the source jar and it seems the commit is in the release, although the ClassCastException still occurred to me

Exception Log Excerpt: https://gist.github.com/Davoleo/1e72b376f352f8baa5719e17e4e49bd2

The block model file: https://github.com/Davoleo/Crystal-Glass/blob/1.20.1/common/src/main/resources/assets/crystalglass/models/block/smart_glass/smart_crystal_glass_off.json

Project source: https://github.com/Davoleo/Crystal-Glass
The project doesn't have any released binary yet.

**Steps to Reproduce**
1. Load the two mods together (Crystal-Glass needs architectury-api)
2. Read the exception in the logs
3. Model doesn't Load

you can also try it out on a different setup that doesn't involve Crystal-Glass, if you don't want to compile the project and if you manage to reproduce it.

If you need anymore info feel free to ask me in a further comment!

**Comment by Davoleo** [comment]
### Update
The issue is specific to the 1.1.1 release on Modrinth, the same release on curseforge works fine.
Perhaps there was a problem during the publishing..?
Since I was using modrinth maven to get the artifact in my dev env I got the broken version.

**Comment by SuperMartijn642** [comment]
Not entirely sure why but there seem to be two files 1.1.1 for Forge 1.20.1 on Modrinth, one uploaded a day after the other. The later uploaded one matches the one on CurseForge.
![image](https://github.com/SuperMartijn642/Fusion/assets/12382965/7dbbe5cd-7059-40d2-9492-053f83df7ba6)

My guess is that I likely reuploaded the file and just forgot to remove the original files on Modrinth, only doing so on CurseForge. Modrinth's API must have just picked the earlier uploaded one as both files have the same version defined.

I have now deleted the earlier uploaded files (for all Minecraft versions and modloaders), so it should be fixed now.
Thank you for reporting the issue!
