### ISSUE TITLE
How do I use the mod?

### ISSUE THREAD

**Issue by Darkeater28** [SuperMartijn642/Fusion#66]
**Version info:**

- Minecraft 1.20.1
- Forge 47.2.0
- No OptiFine
- Mod Version: 1,1,1 

Hi, I installed the mod in a server with friends, but it just doesn't work, It appears installed but when we enter and text the textures doesn't connect; I also tried in a single player world and the same happens, so I dunno if I have to instale something else than the mod, like a texture pack or something.

Please, can someone explain me how to use it? I have it installed in both sides, client (SKLauncher) and server (Aternos).
![imagen_2024-04-22_101950945](https://github.com/SuperMartijn642/Fusion/assets/167791093/a4dd75f7-7f3f-4bd1-a9cf-462a6e742097)

![imagen_2024-04-22_102357501](https://github.com/SuperMartijn642/Fusion/assets/167791093/1ef4128a-ffc2-453c-a042-42a76f7a0f8d)

**Comment by SuperMartijn642** [comment]
Fusion adds additional features which can be used by resource packs. Fusion without a resource pack thus won't do anything.
Additionally, Fusion does not do anything on a server.
For connected textures for vanilla blocks, you can use [Midnighttigger's Default Connected Textures](https://www.curseforge.com/minecraft/texture-packs/mt-ct-d).

**Comment by Darkeater28** [comment]
> Fusion adds additional features which can be used by resource packs. Fusion without a resource pack thus won't do anything. Additionally, Fusion does not do anything on a server. For connected textures for vanilla blocks, you can use [Midnighttigger's Default Connected Textures](https://www.curseforge.com/minecraft/texture-packs/mt-ct-d).

Thank u so much for answering. I installed it on the server side cuz in the page of CurseForge says that is needed but I get it. 
I'll use that resouce pack, can u recommend me another resource pack for Rechiseled by any chance?

**Comment by SuperMartijn642** [comment]
Rechiseled already has connected textures.
