### ISSUE TITLE
[Crash] Optifine incompatibility 

### ISSUE THREAD

**Issue by SHSHYLO** [SuperMartijn642/Fusion#7]
**Version Info**
- Minecraft, 1.19.2
- Rechiseled, 1.1.0a

**Steps to Reproduce**
Have Optifine?

**Crash report (~/logs/latest.log)**
https://gnomebot.dev/paste/1121651126941532260

**Comment by SuperMartijn642** [comment]
Not much I can do as OptiFine is closed source. Just don't use OptiFine. There are other alternatives such as Oculus/Iris.

**Comment by thebikwirm** [comment]
but why not have the fusion mod rechisel worked without it before?

**Comment by YkZen** [comment]
The same thing happens to me too, the problem is that there is no Oculus/Iris in old versions. Example MC 1.12.2. If you can try to solve please, I love this MOD.
