### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by PukPukov** [SuperMartijn642/Fusion#70]

**Comment by SuperMartijn642** [comment]
?

**Comment by PukPukov** [comment]
I mean 1.20.6 support would be great

**Comment by SuperMartijn642** [comment]
Please don't open issues like this. Just spamming empty issues with 1.20.6 as the title to a bunch of repositories is not helpful.
Mods will just release for 1.20.6 when they are ready, these issues aren't going to change anything.

**Comment by PukPukov** [comment]
>Just spamming empty issues with 1.20.6 as the title to a bunch of repositories is not helpful

I think you should look at issues generally as a task (proposal of task), so issue creation is not just a notification (thats the difference between issue creation and for example discord dming), it is also unit of work planning, so when you are creating issue to something that developer already planning to do it is not a useless notification, but formalisation of intentions. 

Also i am not just spamming, i am creating issues after my own testing.
