### ISSUE TITLE
[Question] ... Not working or I didn't understand

### ISSUE THREAD

**Issue by ErythroCraft** [SuperMartijn642/Fusion#74]
**Question**

I was installing your mod and created the example step by step this way [Block Overlay Example](https://github.com/SuperMartijn642/Fusion/wiki/Block-Overlay-Example)

So. This is the result.

assets/example/textures/sand_overlay.png.mcmeta
assets/example/textures/sand_overlay.png
assets/minecraft/models/block/gravel.json

![2024-06-12_23 06 08](https://github.com/SuperMartijn642/Fusion/assets/76217862/5b1bf65e-1eb3-4e59-8dde-f2892a63badd)

**Comment by SuperMartijn642** [comment]
Any texture must be added to the block atlas in order to be used on blocks. Did you add the `example:sand_overlay` to the block atlas?
For context:
https://github.com/SuperMartijn642/Fusion/issues/34#issuecomment-1845531966
https://github.com/SuperMartijn642/Fusion/issues/34#issuecomment-1845570108

**Comment by ErythroCraft** [comment]
Perfect. Thanks a lot.

Maybe you can edit this at the wiki page [Block Overlay Example](https://github.com/SuperMartijn642/Fusion/wiki/Block-Overlay-Example)
