### ISSUE TITLE
[Question] connected sea lanterns

### ISSUE THREAD

**Issue by benaygit** [SuperMartijn642/Fusion#78]
**Question**
hey I'm trying to make a connected sea lantern texture with mcmeta file with the Optional Fusion Overwrites but it's not wanting to work in Minecraft 1.20.1 with forge 47.3.5 and fusion 1.1.1 no optifne but I am using oculus

![Screenshot (55)](https://github.com/user-attachments/assets/0c0ce8e2-373d-42f6-bf5b-8498a69067e9)

![Minecraft Forge_ 1 20 1 - Singleplayer 7_13_2024 10_24_21 PM](https://github.com/user-attachments/assets/ec92a773-faf5-42e9-97c8-9256f4793dd3)

**Comment by SuperMartijn642** [comment]
Did you use a connecting model for the sea lantern?

**Comment by benaygit** [comment]
thanks so much that fixed it
