### ISSUE TITLE
[Bug] Incompatibility with DashLoader (?)

### ISSUE THREAD

**Issue by craftish37** [SuperMartijn642/Fusion#8]
**Version Info**
- Minecraft 1.20.1 / Quilt Loader 0.19.2-beta.2
- Fusion-1.0.0-fabric-mc1.20

**Are you using OptiFine:** Yes or no

*Imagine using Optifine*

**Description of the Bug**

DashLoader enters in IDLE state when used with Fusion (to confirm)

**Steps to Reproduce**
Install both DashLoader and Fusion
Run the game
Check if DashLoader is enabled

**Screenshots**
![image](https://github.com/SuperMartijn642/Fusion/assets/63811617/af3c4dec-9cff-4a89-842e-b169bf57bd19)
![image](https://github.com/SuperMartijn642/Fusion/assets/63811617/f6d2fa96-6d45-4a8f-986d-bf643ce96624)

**Comment by craftish37** [comment]
My bad forgot the [logs](https://github.com/SuperMartijn642/Fusion/files/11886666/latest.log)

**Comment by SuperMartijn642** [comment]
> DashLoader enters in IDLE state

I am not sure what that means

**Comment by craftish37** [comment]
If I remember correctly, when DashLoader fails to cache, it enters IDLE mode instead of crashing the game, permitting to visualise the error message

Appart of this, I don't know much (yet) of the principle of functionnement of DashLoader

**Comment by SuperMartijn642** [comment]
As far as I know, everything should now work fine with newer versions of DashLoader. If there's still issues, please let me know.
Anyways, thank you for reporting the issue!
