### ISSUE TITLE
[Bug] When I have Iris mod instaled textures doesn`t work

### ISSUE THREAD

**Issue by LUVSka2** [SuperMartijn642/Fusion#81]
**Version Info** 
- Minecraft, 1.21
- Fusion, 1.1.1

**Are you using OptiFine:** Yes or no
No

**Description of the Bug**

Basically when Iris is in the game the Fusion mod doesnt work, i noticed it when i removed it from mods folder to see and fusion begin to work properly

**Comment by SuperMartijn642** [comment]
What exactly do you means by 'the Fusion mod doesnt work' and 'textures doesn`t work'?
Could you share the logs from with Iris installed? And also, what modloader are you using?

**Comment by LUVSka2** [comment]
> What exactly do you means by 'the Fusion mod doesnt work' and 'textures doesn`t work'? Could you share the logs from with Iris installed? And also, what modloader are you using?

Im using fabric, but basically when i have iris active the textures doesnt connect in rechiseled mod…

**Comment by SuperMartijn642** [comment]
If you are using Sodium, you will have to install Indium. Sodium breaks any mod using the Fabric rendering API.

**Comment by Nigel2392** [comment]
Hey! Sorry to "revive" this. I'm using NeoForge with Sodium on 1.21.1. Also have fusion and connectedglass installed; it doesn't work. Do you know if there's any type of alternative like Indium? (if the rendering engine also gets monkeypatched like with fabric). Could it be an issue with resource packs?

**Comment by SuperMartijn642** [comment]
@Nigel2392 Connected Glass adds new glass blocks. It does not change vanilla glass.
