### ISSUE TITLE
[Crash] Cannot read field "top" because "connections" is null

### ISSUE THREAD

**Issue by Midnighttigger** [SuperMartijn642/Fusion#84]
Version Info:
Forge/Neoforge, known to crash on 1.20.1, 1.21.1 Neoforge and Forge
1.20.4 Neoforge strangely doesnt crash
Fabric doesnt seam to crash, other versions of neoforge/forge could crash

Are you using OptiFine:
No

Steps to Reproduce:
See Version Info, then run just Fusion + 
[Midnighttiggers-FCT-Default_1.20_V5.zip](https://github.com/user-attachments/files/17117257/Midnighttiggers-FCT-Default_1.20_V5.zip)

Crash report (~/logs/latest.log):
[crash-2024-09-24_16.32.49-client.txt](https://github.com/user-attachments/files/17117230/crash-2024-09-24_16.32.49-client.txt)

**Comment by xAphex** [comment]
Same issue happening here

**Comment by Midnighttigger** [comment]
I have fixed it because I remove connections for textures which didn't exist in the model

**Comment by Midnighttigger** [comment]
It seams the issue is bigger than this and also effects match_state, will make a more specific issue request
