### ISSUE TITLE
[Question] Texture order gets flipped when connecting textures on a 3 sided block. Any way I can fix this?

### ISSUE THREAD

**Issue by Gogo64pro** [SuperMartijn642/Fusion#86]
Texture order gets flipped when connecting textures on a 3 sided block. Any way I can fix this?
![image](https://github.com/user-attachments/assets/6ed6cf5d-8009-49fd-9715-7c1f0b4a64c7)
![image](https://github.com/user-attachments/assets/b30626a9-0f44-4079-ae0f-f28322c140a4)
I am using the simple texture atlas

**Comment by SuperMartijn642** [comment]
Do you have uvLock enabled in the model?

My guess is that the model gets rotated in the blockstate for the command block. Fusion tries to account for this when checking the connections, but it is currently broken when uvLock is enabled.

**Comment by Gogo64pro** [comment]
> Do you have uvLock enabled in the model?
> 
> My guess is that the model gets rotated in the blockstate for the command block. Fusion tries to account for this when checking the connections, but it is currently broken when uvLock is enabled.

How do I disable that `"uvLock": false` in the model file doesn't work

**Comment by SuperMartijn642** [comment]
Ah if it is not explicitly set to true, then it should be false I believe. Likely just some bug then.
Could you share what you currently have for the model/textures for the command block?
Also, what Minecraft version, what modloader, and what version of Fusion are you using?

**Comment by Gogo64pro** [comment]
`{
	"parent": "minecraft:block/template_command_block",
	"textures": {
		"back": "minecraft:block/command_block_back",
		"front": "minecraft:block/command_block_front",
		"side": "minecraft:block/command_block_side"
	},
	"loader": "fusion:model",
	"type": "connecting",
    "uvLock": false,
	"connections": [
		{
			"type": "is_same_state"
		}
	]
}
` 
for the model
![command_block_side](https://github.com/user-attachments/assets/fbe0934a-4bdb-4d33-ac51-8e4a5aacc1e1) for the image (it's temporary),
`{
   "fusion": {
      "type": "connecting",
      "layout": "simple"
   }
}` for the mcmeta
Currently it's only if they are facing the same direction, but I want to make them be angled if the next command block is a chain one and it's not conditional, but I'll figure that out later.

**Comment by Gogo64pro** [comment]
Minecraft 1.20.1,
Forge: 47.3.0,
Fusion:1.1.1

**Comment by SuperMartijn642** [comment]
I indeed get the same result with the current version of Fusion for Forge 1.20.1.
I am currently working on an update where I have redone pretty much all the connected texture handling code and it seems to work fine there, so definitely just a bug with Fusion.

I am not too sure where the bug comes from exactly. I do have some pillar-like blocks in Rechiseled as well which also use the simple layout and they haven't had any issues like this. I also haven't had anyone report this before, so I think you just got unlucky.
Seeing as it already works correctly with the update I am working on, I don't wanna spent too much time looking into it. I am afraid you'll have to wait until I am done with that 😅

**Comment by Gogo64pro** [comment]
> I indeed get the same result with the current version of Fusion for Forge 1.20.1. I am currently working on an update where I have redone pretty much all the connected texture handling code and it seems to work fine there, so definitely just a bug with Fusion.
> 
> I am not too sure where the bug comes from exactly. I do have some pillar-like blocks in Rechiseled as well which also use the simple layout and they haven't had any issues like this. I also haven't had anyone report this before, so I think you just got unlucky. Seeing as it already works correctly with the update I am working on, I don't wanna spent too much time looking into it. I am afraid you'll have to wait until I am done with that 😅

Don't worry I just want to know is you are adding a way 2 different textures can be connected. I want the side to be able to connect to the back and front(different textures), and I wasn't able to find a way to do it with the current version

**Comment by SuperMartijn642** [comment]
You can make the textures connect to whatever you want. Just specify the connection predicates in the model file https://github.com/SuperMartijn642/Fusion/wiki/Default-Model-Types#connection-predicates

**Comment by Gogo64pro** [comment]
> 

> You can make the textures connect to whatever you want. Just specify the connection predicates in the model file https://github.com/SuperMartijn642/Fusion/wiki/Default-Model-Types#connection-predicates

Oh, okay
