### ISSUE TITLE
[Bug] [1.21.1]Connected Glass and Fusion overwrite the glass Recipe

### ISSUE THREAD

**Issue by Periam** [SuperMartijn642/Fusion#88]
**Version Info**
- Minecraft, 1.21.1.
- Fusion, fusion-1.1.1a-neoforge-m1.21.1

-*Are you using OptiFine:** No

**Description of the Bug**
After installing the latest version of the mods and depencies the recipe for glass was overwrite and disappeared 

**Steps to Reproduce**
Install mods
launch game
Create world
Look for glass recipe

[latest.log](https://github.com/user-attachments/files/17576647/latest.log)

**Screenshots**
![image](https://github.com/user-attachments/assets/f459c4d8-7a7a-4b50-91ef-9fb81ced689e)

**Comment by SuperMartijn642** [comment]
What exactly is the issue here?

**Comment by Periam** [comment]
when I installed the mod, the recipe for glass disappeared, I could not craft it by burning sand.

**Comment by SuperMartijn642** [comment]
Wait actually, are you reporting an issue for Connected Glass or for Fusion? Connected Glass is supposed to add the recipe you show to turn its glass back into vanilla glass.

**Comment by Periam** [comment]
mm the issue appeared after installing connected glass that installed Fusion.. I try to search for a config. to check and could not find.. so I do not know which mod is breaking the normal glass recipe.

**Comment by SuperMartijn642** [comment]
> when I installed the mod, the recipe for glass disappeared, I could not craft it by burning sand.

Fusion does not change any recipes. The only thing Fusion does is expand the capabilities of resource packs with features such as connected textures.

Connected Glass only adds an additional recipe to turn its glass back into vanilla glass. It does not modify any vanilla recipes for glass.
Even in your screenshot from JEI, it shows there's a furnace recipe.

**Comment by Periam** [comment]
I am sorry for the rush report, I was kind of in a hurry and frustrated, I will keep  looking. Thanks for the quick answer.
