### ISSUE TITLE
[Bug] Clear Glass and Clean Connected Glass resource packs don’t work with Fusion

### ISSUE THREAD

**Issue by Nevrai** [SuperMartijn642/Fusion#89]
When using the [Clear Glass with Connected Textures](https://www.curseforge.com/minecraft/texture-packs/clear-glass-pack) or [Clean Connected Glass](https://modrinth.com/resourcepack/clean-connected-glass) resource packs, glass blocks and panes don’t have connected textures. Tested with no mods installed except Fusion. OptiFine is not installed.

These packs are made for OptiFine, so this may be more of an issue on the creators of these two resource packs’ part rather than on Fusion’s, but it would be fabulous if Fusion could be updated to mimic OptiFine’s implementation of connected textures so it can support resource packs that weren’t made for Fusion. I haven’t been able to find a connected glass resource pack that works.

### Versions
* **Minecraft**: 1.20.1
* **Forge**: 47.3.11
* **Fusion**: 1.1.1

**Comment by SuperMartijn642** [comment]
Fusion indeed does not use OptiFine's format, so you will need a resource pack made for Fusion.
[Midnighttigger's Default Connected Textures](https://www.curseforge.com/minecraft/texture-packs/mt-ct-d) adds connected textures for a bunch of vanilla blocks including glass.
