### ISSUE TITLE
[Bug] Glass Panes unable to do CTM

### ISSUE THREAD

**Issue by Midnighttigger** [SuperMartijn642/Fusion#9]
**Version Info**
- Minecraft, 1.20.1 Forge
- fusion-1.0.2-forge-mc1.20

**Are you using OptiFine:** No

**Description of the Bug**
Glass panes are unable to do CTM

**Steps to Reproduce**
[pack.zip](https://github.com/SuperMartijn642/Fusion/files/11935127/pack.zip)

**Screenshots**
[...](https://cdn.discordapp.com/attachments/779005278272225300/1125170422166593587/image.png)

**Comment by SuperMartijn642** [comment]
Turns out the parent models weren't always getting loaded, so the model simply had no elements.
Fixed now in version 1.0.3.
Thank you for reporting the issue!
