### ISSUE TITLE
[Bug] Block Overlay not affecting all surrounding blocks

### ISSUE THREAD

**Issue by guivnf** [SuperMartijn642/Fusion#93]
**Version Info**
- Minecraft: 1.20.1
- Fusion: 1.1.1
- Forge: 47.3.12

**Are you using OptiFine:** No

**Description of the Bug**
The issue itself consists of block overlays not affecting all targeted blocks that are surrounding it. So for example, the overlay of a dirt block on top of stone blocks, only affects a few specific stone blocks that surround the dirt block. 

Look at the image for example:
![image](https://github.com/user-attachments/assets/62547946-1170-48a1-b01e-729ead680e76)
As you may note, the blocks without colors on top of them are not affected by the overlay as i expected.

This is the texture file i made to be able to reference each block side:
![image](https://github.com/user-attachments/assets/ae39369a-2b05-425b-9b46-33f08cffb9b6)

The red blob is working just fine as it's not supposed to be affected by any overlays, but there are a few random blocks that are just not affected at all, which's really odd

**Steps to Reproduce**
1. download the textures:
![dirt_overlay](https://github.com/user-attachments/assets/b1fb7b40-b4e6-4099-89c5-6619035d3329)
2. Apply this to the dirt_overlay.png.mcmeta
```json
{
   "fusion": {
      "type": "connecting",
      "layout": "full",
      "render_type": "cutout"
   }
}
```
3. add the textures to the texture atlas
4. add this to the stone model json
```json
{
   "loader": "fusion:model",
   "type": "connecting",
   "parent": "block/block",
   "textures": {
      "particle": "#all",
      "all": "minecraft:block/stone",
      "dirt_overlay": "minecraft:block/ct/dirt_overlay"
   },
   "connections": {
      "dirt_overlay": [
         {
            "type": "match_block",
            "block": "minecraft:dirt"
         }
      ]
   },
   "elements": [
      {
         "from": [ 0, 0, 0 ],
         "to": [ 16, 16, 16 ],
         "faces": {
            "down":  { "texture": "#all", "cullface": "down" },
            "up":   { "texture": "#all", "cullface": "up" },
            "north": { "texture": "#all", "cullface": "north" },
            "south": { "texture": "#all", "cullface": "south" },
            "west":  { "texture": "#all", "cullface": "west" },
            "east":  { "texture": "#all", "cullface": "east" }
         }
      },
      {
         "from": [ 0, 0, 0 ],
         "to": [ 16, 16, 16 ],
         "faces": {
            "up":   { "texture": "#dirt_overlay", "cullface": "up" }
         }
      }
   ]
}
```

**Screenshots**

![image](https://github.com/user-attachments/assets/23836cf6-0efc-4f97-99d5-cccbfba9414d)
Blocks without color blob are glitched

![image](https://github.com/user-attachments/assets/3886c5ef-a02f-4088-9ed0-553d83bef4ca)

**Comment by guivnf** [comment]
I just realized that the blocks have some weird generation pattern simmilar to the flower patches...
![image](https://github.com/user-attachments/assets/65d52f31-8a80-4f5b-be43-ac08c678a630)

**Comment by SuperMartijn642** [comment]
As discussed on Discord, the blockstate file for stone uses two models, `minecraft:block/stone` and `minecraft:block/stone_mirrored`, which are randomly rotated 180 degrees.
```json
{
  "variants": {
    "": [
      {
        "model": "minecraft:block/stone"
      },
      {
        "model": "minecraft:block/stone_mirrored"
      },
      {
        "model": "minecraft:block/stone",
        "y": 180
      },
      {
        "model": "minecraft:block/stone_mirrored",
        "y": 180
      }
    ]
  }
}
```
As only the `minecraft:block/stone` model was changed and not `minecraft:block/stone_mirrored`, only those stone blocks which randomly got assigned the `minecraft:block/stone` model showed the overlay.
